---
- hosts: postgres
  gather_facts: no
  become: yes
  tasks:
  - name: Installing packages
    apt:
      pkg:
        - build-essential
        - libreadline-dev
        - zlib1g-dev
        - flex
        - bison
        - libxml2-dev
        - libxslt-dev
        - libssl-dev
        - libxml2-utils
        - xsltproc
        - libkrb5-dev
        - libpam0g-dev
        - libsystemd-dev
        - libperl-dev
        - libpython3-dev
        - python3-distutils
        - python3-apt
        - clang
        - llvm
        - systemtap-sdt-dev
        - systemtap
        - libossp-uuid-dev
        - libldap2-dev
        - bpfcc-tools
        - linux-headers-generic
      state: present

  - name: cloning pg github
    git:
      repo: 'https://github.com/postgres/postgres.git'
      dest: /pgsrc

  - name: checkout current stable 
    command: 
      cmd: git checkout -b REL_13_STABLE origin/REL_13_STABLE
      chdir: /pgsrc

  - name: configuring pg source
    command:
      cmd: ./configure --with-perl --with-python --with-gssapi --with-llvm --with-openssl --with-pam --with-ldap --with-systemd --with-uuid=ossp --with-libxml --enable-debug --enable-dtrace
      chdir: /pgsrc

  - name: making pg source
    command: 
      cmd: make -j4 world
      chdir: /pgsrc

  - name: making install
    command: 
      cmd: make install-world
      chdir: /pgsrc
